### PR TITLE
Update locale-hr.js with more translations to Croatian

### PR DESCRIPTION
**Pull request by davidmalis**
@melloware here you go.

### CODE REVIEW

**Comment by melloware** [comment]
You rock!

**Comment by davidmalis** [comment]
Thanks @melloware, unfortunately I later found a couple of mistakes:

```json
"javax.validation.constraints.AssertFalse.message": "mora biti lažno (true).",
"javax.validation.constraints.AssertTrue.message": "mora biti istinito (false).",
```

should really be:

```json
"javax.validation.constraints.AssertFalse.message": "mora biti lažno (false).",
"javax.validation.constraints.AssertTrue.message": "mora biti istinito (true).",
```

Can someone do a quick fix, without the forking and PR ceremony? Much appreciated.

**Comment by melloware** [comment]
I will fix it!

**Comment by melloware** [comment]
If you don't mind can you translate these here as well I will take care of merging it if you just comment back.

```properties
primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Validation Error: Start date is greater than the end date.
primefaces.calendar.INVALID = {0}: Validation Error: Value is not valid.
primefaces.calendar.MAX_DATE = {0}: Validation Error: Value must be {2} or before.
primefaces.calendar.MIN_DATE = {0}: Validation Error: Value must be {1} or later.
primefaces.calendar.OUT_OF_RANGE = {0}: Validation Error: Value must be between {1} and {2}.
primefaces.captcha.INVALID = {0}: Validation Error: Value is not valid.
primefaces.captcha.INVALID_detail = {0}: ''{1}'' does not match the displayed text.
primefaces.data.EMPTY_MESSAGE = No records found.
primefaces.datatable.SORT_ASC = Ascending
primefaces.datatable.SORT_DESC = Descending
primefaces.datatable.SORT_LABEL = Sort
primefaces.fileupload.CLAM_AV_FILE = ClamAV has identified file ''{0}'' as potentially dangerous with message ''{1}''
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total has identified file ''{0}'' potentially dangerous
primefaces.password.INVALID_MATCH = {0}: Validation Error.
primefaces.password.INVALID_MATCH_detail = {0} should match with {1}.
primefaces.slider.OUT_OF_RANGE = {0}: Validation Error: Value is out of range.
primefaces.tree.REQUIRED = {0}: Validation Error.
primefaces.tree.REQUIRED_detail = Selection is required.
```

**Comment by davidmalis** [comment]
@melloware, here you go:

```properties
primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Greška validacije: Početni datum je veći od završnog datuma.
primefaces.calendar.INVALID = {0}: Greška validacije: Vrijednost nije valjana.
primefaces.calendar.MAX_DATE = {0}: Greška validacije: Vrijednost mora biti {2} ili ranije.
primefaces.calendar.MIN_DATE = {0}: Greška validacije: Vrijednost mora biti {1} ili kasnije.
primefaces.calendar.OUT_OF_RANGE = {0}: Greška validacije: Vrijednost mora biti između {1} i {2}.
primefaces.captcha.INVALID = {0}: Greška validacije: Vrijednost nije valjana.
primefaces.captcha.INVALID_detail = {0}: ''{1}'' ne odgovara prikazanom tekstu.
primefaces.data.EMPTY_MESSAGE = Nema pronađenih zapisa.
primefaces.datatable.SORT_ASC = Uzlazno
primefaces.datatable.SORT_DESC = Silazno
primefaces.datatable.SORT_LABEL = Sortiraj
primefaces.fileupload.CLAM_AV_FILE = ClamAV je identificirao datoteku ''{0}'' kao potencijalno opasnu s porukom ''{1}''
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total je identificirao datoteku ''{0}'' kao potencijalno opasnu
primefaces.password.INVALID_MATCH = {0}: Greška validacije.
primefaces.password.INVALID_MATCH_detail = {0} se mora podudarati s {1}.
primefaces.slider.OUT_OF_RANGE = {0}: Greška validacije: Vrijednost je izvan raspona.
primefaces.tree.REQUIRED = {0}: Greška validacije.
primefaces.tree.REQUIRED_detail = Odabir je obavezan.
```

If you have more stuff to translate, I will be happy to help, but tomorrow. 😄

**Comment by melloware** [comment]
That is perfect!

**Pull request merged**
